### ISSUE TITLE
Update the readme file to explain the repo and how to get it setup.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/utahjs-website#22]

**Comment by AlexanderPuhl** [comment]
Lets wait until this project is closer to being finished before doing this task.

**Comment by jgbowser** [comment]
I want to start on this one, maybe at least the setup part. I want to try to use an AI tool that generates documentation for this and see how it goes.

**Comment by AlexanderPuhl** [comment]
For sure @jgbowser, let me know how that goes! :)

**Comment by AlexanderPuhl** [comment]
@jgbowser, just approved the pull request, do you want to leave this issue open?
