### ISSUE TITLE
Figure out how to make metadata more dynamic.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/utahjs-website#31]
Would like to store metadata in Sanity and pull that into NextJS.

**Comment by jgbowser** [comment]
@AlexanderPuhl could you give me a bit more info on this one? Is this related to the issues with dynamic metadata not working as expected and the `'use client'` pages title metadata needing to be set? Or is there more to this in relation to Sanity?

**Comment by AlexanderPuhl** [comment]
@jgbowser, I was having some issues with the main speaker page metadata. It's currently hard coded, but I would like it to be flexible. In that speaker page's case, I was trying to get the latest speakers, pull the year and populate the metadata with that year. Right now it's hard coded to 2023.

Maybe this will be a speerate issue, but I would like to store metadata in sanity for stuff like the site title, description, facebook/twitter meta properties.
