### ISSUE TITLE
Create spots in the pages schema for header meta data.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/utahjs-website#48]
Then pull that data in on the front end and populate the header w/ out having to hard code that stuff. Stuff like this:

![image](https://github.com/FreeCodeCamp-SLC/utahjs-website/assets/22256166/7dde12f7-01ab-4b76-aeaf-383e69b5206d)

**Comment by coltonbonner** [comment]
@AlexanderPuhl I added a branch for this. 

Home Page Layout: Set a default metadata object
Conference Page: Set new metadata from Sanity info

Figured I'd ask now before going through the other pages, but I could also set up a separate Metadata field on sanity for each page if it needs to be different from the page content. What do you think?

**Comment by AlexanderPuhl** [comment]
@bwreDev Ya we do want a metaata section for each page. I also figured we would have a global metadata section in the site settings somewhere. The ones for each page will override any global metadata.
